language: node_js

node_js:
  - '8.11.3'

  cache:
  yarn: true
  directories:
    - node_modules

#script:
  #- yarn test #if exist any test
  #- bash ./deploy.sh #If you want deploy application anywhere